VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes

OLED_ENABLE         = yes
EXTRAKEY_ENABLE     = yes
WPM_ENABLE = yes
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
CONSOLE_ENABLE	= yes
